### ISSUE TITLE
Some question about the project

### ISSUE THREAD

**Issue by thunanguyen** [JYPark09/BabaIsAgent#26]
HI, I just want to ask how to use the built library (through python?) and what is the status of the project?

**Comment by JYPark09** [comment]
If you build project with CMake, you can get the python extension module file. (maybe it is in lib directory) Now, we wrote the Python API but only Korean. But you'll find it helpful to refer to [this](https://github.com/JYPark09/BabaIsAgent/blob/master/Extension/BabaAgent/environment.py)

Sadly, this project is suspended. But hopefully within a few months, we will resume this project.

**Comment by thunanguyen** [comment]
Wow, thanks for the fast reply, I am experimenting with the python api right now. Hopefully, if I’m free, I’d love to contribute to the repo.

**Comment by utilForever** [comment]
@thunanguyen Hello, I'm making RL environment for Baba Is You. :)
(https://github.com/utilForever/baba-is-auto)
